[build]
  functions = "functions"
  publish = "public"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "ADMIN_USERNAME"

[functions]
  # We switch to the standard ZIP bundler so it stops compressing the database packages
  node_bundler = "zisi"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/server/:splat"